### ISSUE TITLE
Isolate language and domain-specific keywords

### ISSUE THREAD

**Issue by marfox** [dbpedia/list-extractor#1]
In [mapper.py](../blob/master/mapper.py), specifically [here](../blob/master/mapper.py#L23) and [here](../blob/master/mapper.py#L30), the hardcoded keywords `bibliography` and `opere` should be pulled out from the specific functions, to facilitate the implementation of different languages and different domains.

I would put them in constants, clearly visible at the top of the script, right after the imports:

``` python
import utilities

BIBLIOGRAPHY = {
    'en': ['bibliography'],
    'it': ['opere', 'bibliografia']
}
```

Then, the language-specific functions `select_mapping_en` and `select_mapping_it` should be merged into one, with an additional `language` parameter.

**Comment by Feddie** [comment]
Accepted, mapper module updated!
